# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: grupo12
# "app" enables Serverless Framework Dashboard features and sharing them with other Services.
app: grupo12

service: boleta-service

provider:
  name: aws
  runtime: nodejs20.x
  region: us-east-1
  iam:
    role:
      statements:
        - Effect: Allow
          "Action": 
          - s3:PutObject
          - s3:PutObjectAcl 
          Resource: arn:aws:s3:::imprimir-boletas/* 
          
functions:
  generateBoleta:
    handler: generateBoleta.handler
    events:
      - http:
          path: /generateBoleta
          method: post
          cors: true
