name: Deploy to AWS

on: 
  push:
    branches:
      - main  

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'  

      - name: Install dependencies
        run: |
          cd boletas-pdf 
          npm install

      - name: Install Serverless globally
        run: |
          npm install -g serverless 

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1  

      - name: Run tests
        env:
          SERVERLESS_ACCESS_KEY: ${{ secrets.SERVERLESS_ACCESS_KEY }}  
        run: |
          cd boletas-pdf
          serverless invoke local -f generateBoleta --data '{"body": "{\"liga\": \"Grupo 19\", \"usuario\": { \"nombre\": \"Javi Paz\",  \"email\": \"javi@example.com\"}, \"partido\": {\"equipo1\": \"Equipo A\", \"equipo2\": \"Equipo B\", \"ubicacion\": \"Estadio Nacional\"}, \"valorTotal\": 150.00}"}'

      - name: Deploy to AWS
        env:
          SERVERLESS_ACCESS_KEY: ${{ secrets.SERVERLESS_ACCESS_KEY }} 
        run: |
          cd boletas-pdf
          serverless deploy
